foreground #E9C6B2
background #141318
selection_foreground #141318
selection_background #E9C6B2
cursor #E9C6B2
cursor_text_color #141318
url_color #ff252b

color0 #141318
color1 #272228
color2 #6D3D3D
color3 #FFF9F0
color4 #332323
color5 #7d0f1f
color6 #a8141d
color7 #d3181c
color8 #ff252b
color9 #E9C6B2

active_tab_foreground   #141318
active_tab_background   #a8141d
inactive_tab_foreground #E9C6B2
inactive_tab_background #272228
tab_bar_background      #141318
